sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dkmaruthi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dkmaruthi/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'docker'
  env: 'docker-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-275166638116'
  bucket_path: 'docker'
  on:
    branch: master

    #acces_key_id: $AWS_ACCESS_KEY
    acces_key_id: "$AWS_ACCESS_KEY"
    secure_key_id: "$AWS_SECRET_KEY"

